# Initial Analysis

## Business Understanding

## Data Understanding

### Imports and Configurations

In [2]:
import sys
import os

sys.path.append(os.path.join('..','..'))
import toolkit as tk

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

### Glossary
* id
* P-PDG
* P-TPT
* T-TPT
* P-MON-CKP
* T-JUS-CKP
* P-JUS-CKGL
* T-JUS-CKGL
* QGL
* class

In [3]:
real_instances, simulated_instances, drawn_instances = tk.get_all_labels_and_files()
tk.load_instance(real_instances[0])

,label,well,id,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,T-JUS-CKGL,QGL,class
timestamp,,,,,,,,,,,,
2017-06-25 22:01:27,0,WELL-00002,20170625220127,0.0,8698015.0,117.6015,2142158.0,75.63453,2310426.0,NaN,0.0,0
2017-06-25 22:01:28,0,WELL-00002,20170625220127,0.0,8698015.0,117.6014,2172395.0,75.65491,2310427.0,NaN,0.0,0
2017-06-25 22:01:29,0,WELL-00002,20170625220127,0.0,8698015.0,117.6013,2202631.0,75.67529,2310427.0,NaN,0.0,0
2017-06-25 22:01:30,0,WELL-00002,20170625220127,0.0,8698015.0,117.6012,2180472.0,75.69567,2310427.0,NaN,0.0,0
2017-06-25 22:01:31,0,WELL-00002,20170625220127,0.0,8698015.0,117.6011,2158313.0,75.71606,2310428.0,NaN,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-06-26 02:59:56,0,WELL-00002,20170625220127,0.0,8573995.0,117.7521,1354130.0,76.21077,2319469.0,NaN,0.0,0
2017-06-26 02:59:57,0,WELL-00002,20170625220127,0.0,8574327.0,117.7520,1338698.0,76.24621,2319470.0,NaN,0.0,0
2017-06-26 02:59:58,0,WELL-00002,20170625220127,0.0,8574660.0,117.7519,1323267.0,76.28165,2319470.0,NaN,0.0,0
2017-06-26 02:59:59,0,WELL-00002,20170625220127,0.0,8574992.0,117.7518,1307835.0,76.31710,2319471.0,NaN,0.0,0
2017-06-26 03:00:00,0,WELL-00002,20170625220127,0.0,8575325.0,117.7517,1330259.0,76.28115,2319471.0,NaN,0.0,0

## Data Preparation

## Modeling

## Evaluation